### ISSUE TITLE
Why rad+1 when retrieving the ball nodes?

### ISSUE THREAD

**Issue by mr-devs** [alexbovet/information_diffusion#1]
https://github.com/alexbovet/information_diffusion/blob/2db844bc5cd61716fae78c329b93854c1c7b7659/CIcython.pyx#L528

Hi Alex, I'm confused why this line of code passes `rad+1` instead of just `rad`? Based on the below `<=` line from `CIcython` $\rightarrow$ `get_ball()`, (at least as I understand the code, and I'm just learning it today) this would include nodes one step outside the previously defined radius. 

https://github.com/alexbovet/information_diffusion/blob/2db844bc5cd61716fae78c329b93854c1c7b7659/CIcython.pyx#L231

Am I misunderstanding the definition of the ball? or the code? 😅

---

I ask this because I am currently attempting to implement a version of your CI algorithm using `igraph-python`.

Thanks!

**Comment by alexbovet** [comment]
Hi,

This is only done to get the nodes whose CI score needs to be updated once a top CI node has been removed. Since the degree of the nodes at a distance 1 from a removed node changes, the CI score of nodes at a distance rad+1 also changes when the node is removed. I hope it's clear!

Best,

Alex
